baseURL = "https://notajely.github.io/camera-archive/"
languageCode = "zh-cn"
title = "FilmCameraDB"
theme = "PaperMod"

[pagination]
  pagerSize = 20

[params]
  homeInfoParams = {Title = "Camera File"}
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  mainSections = ["cameras"]

[taxonomies]
  tag = "tags"
  brand = "brands"
  mount = "mounts"
  film_format = "formats"
  year = "years"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.3
  minMatchCharLength = 2
  keys = ["title", "summary", "params.specs.mount", "brands"]

[[menus.main]]
  name = "Cameras"
  url = "/cameras/"
  weight = 1

[[menus.main]]
  name = "Brands"
  url = "/brands/"
  weight = 2

[[menus.main]]
  name = "Library"
  url = "library"
  weight = 20

[[menus.main]]
  name = "Search"
  url = "search"
  weight = 30
